name: JavaCI

on: 
  push:
    branches:
      - master

jobs:
  before_testing:
    runs-on: [ubuntu-16.04]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml 
    - name: list current folder
      run: ls -la  
  
  after_testing:
      runs-on: [ubuntu-16.04]
      needs: [before_testing]
     
      steps:
      - name: Print Hello
        run: echo "Hello!"
 
   
